config/routes.rb
Rails.application.routes.draw do
  resources :date_infecteds
  resources :diseases
  resources :animals
  resources :owners
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :owner
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/date_infected.rb
class DateInfected < ApplicationRecord
  belongs_to :animal
  belongs_to :disease
end

app/models/disease.rb
class Disease < ApplicationRecord
end

app/models/owner.rb
class Owner < ApplicationRecord
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :owner_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/date_infecteds_controller.rb
class DateInfectedsController < ApplicationController
  before_action :set_date_infected, only: [:show, :edit, :update, :destroy]

  # GET /date_infecteds
  # GET /date_infecteds.json
  def index
    @date_infecteds = DateInfected.all
  end

  # GET /date_infecteds/1
  # GET /date_infecteds/1.json
  def show
  end

  # GET /date_infecteds/new
  def new
    @date_infected = DateInfected.new
  end

  # GET /date_infecteds/1/edit
  def edit
  end

  # POST /date_infecteds
  # POST /date_infecteds.json
  def create
    @date_infected = DateInfected.new(date_infected_params)

    respond_to do |format|
      if @date_infected.save
        format.html { redirect_to @date_infected, notice: 'Date infected was successfully created.' }
        format.json { render :show, status: :created, location: @date_infected }
      else
        format.html { render :new }
        format.json { render json: @date_infected.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /date_infecteds/1
  # PATCH/PUT /date_infecteds/1.json
  def update
    respond_to do |format|
      if @date_infected.update(date_infected_params)
        format.html { redirect_to @date_infected, notice: 'Date infected was successfully updated.' }
        format.json { render :show, status: :ok, location: @date_infected }
      else
        format.html { render :edit }
        format.json { render json: @date_infected.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /date_infecteds/1
  # DELETE /date_infecteds/1.json
  def destroy
    @date_infected.destroy
    respond_to do |format|
      format.html { redirect_to date_infecteds_url, notice: 'Date infected was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_date_infected
      @date_infected = DateInfected.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def date_infected_params
      params.require(:date_infected).permit(:date_infected, :animal_id, :disease_id)
    end
end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  before_action :set_disease, only: [:show, :edit, :update, :destroy]

  # GET /diseases
  # GET /diseases.json
  def index
    @diseases = Disease.all
  end

  # GET /diseases/1
  # GET /diseases/1.json
  def show
  end

  # GET /diseases/new
  def new
    @disease = Disease.new
  end

  # GET /diseases/1/edit
  def edit
  end

  # POST /diseases
  # POST /diseases.json
  def create
    @disease = Disease.new(disease_params)

    respond_to do |format|
      if @disease.save
        format.html { redirect_to @disease, notice: 'Disease was successfully created.' }
        format.json { render :show, status: :created, location: @disease }
      else
        format.html { render :new }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diseases/1
  # PATCH/PUT /diseases/1.json
  def update
    respond_to do |format|
      if @disease.update(disease_params)
        format.html { redirect_to @disease, notice: 'Disease was successfully updated.' }
        format.json { render :show, status: :ok, location: @disease }
      else
        format.html { render :edit }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diseases/1
  # DELETE /diseases/1.json
  def destroy
    @disease.destroy
    respond_to do |format|
      format.html { redirect_to diseases_url, notice: 'Disease was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disease
      @disease = Disease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disease_params
      params.require(:disease).permit(:description)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_infecteds_helper.rb
module DateInfectedsHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :owner_id %>
    <%= form.collection_select :owner_id, Owner.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.name %></td>
        <td><%= animal.owner.name %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @animal.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @animal.owner.name %>
</p>

<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/date_infecteds/_form.html.erb
<%= form_with(model: date_infected, local: true) do |form| %>
  <% if date_infected.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(date_infected.errors.count, "error") %> prohibited this date_infected from being saved:</h2>

      <ul>
        <% date_infected.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date_infected %>
    <%= form.text_field :date_infected %>
  </div>

  <div class="field">
    <%= form.label :animal_id %>
    <%= form.collection_select :animal_id, Animal.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :disease_id %>
    <%= form.collection_select :disease_id, Disease.all, :id, :description  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/date_infecteds/edit.html.erb
<h1>Editing Date Infected</h1>

<%= render 'form', date_infected: @date_infected %>

<%= link_to 'Show', @date_infected %> |
<%= link_to 'Back', date_infecteds_path %>

app/views/date_infecteds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Date Infecteds</h1>

<table>
  <thead>
    <tr>
      <th>Date infected</th>
      <th>Animal</th>
      <th>Disease</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @date_infecteds.each do |date_infected| %>
      <tr>
        <td><%= date_infected.date_infected %></td>
        <td><%= date_infected.animal.name %></td>
        <td><%= date_infected.disease.description %></td>
        <td><%= link_to 'Show', date_infected %></td>
        <td><%= link_to 'Edit', edit_date_infected_path(date_infected) %></td>
        <td><%= link_to 'Destroy', date_infected, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Date Infected', new_date_infected_path %>

app/views/date_infecteds/new.html.erb
<h1>New Date Infected</h1>

<%= render 'form', date_infected: @date_infected %>

<%= link_to 'Back', date_infecteds_path %>

app/views/date_infecteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date infected:</strong>
  <%= @date_infected.date_infected %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @date_infected.animal.name %>
</p>

<p>
  <strong>Disease:</strong>
  <%= @date_infected.disease.description %>
</p>

<%= link_to 'Edit', edit_date_infected_path(@date_infected) %> |
<%= link_to 'Back', date_infecteds_path %>

app/views/diseases/_form.html.erb
<%= form_with(model: disease, local: true) do |form| %>
  <% if disease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(disease.errors.count, "error") %> prohibited this disease from being saved:</h2>

      <ul>
        <% disease.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/diseases/edit.html.erb
<h1>Editing Disease</h1>

<%= render 'form', disease: @disease %>

<%= link_to 'Show', @disease %> |
<%= link_to 'Back', diseases_path %>

app/views/diseases/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Diseases</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diseases.each do |disease| %>
      <tr>
        <td><%= disease.description %></td>
        <td><%= link_to 'Show', disease %></td>
        <td><%= link_to 'Edit', edit_disease_path(disease) %></td>
        <td><%= link_to 'Destroy', disease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disease', new_disease_path %>

app/views/diseases/new.html.erb
<h1>New Disease</h1>

<%= render 'form', disease: @disease %>

<%= link_to 'Back', diseases_path %>

app/views/diseases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @disease.description %>
</p>

<%= link_to 'Edit', edit_disease_path(@disease) %> |
<%= link_to 'Back', diseases_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InclassProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


    <style>
      body {
        background-color: lightblue;
      }
    </style>
  </head>

  
  </body>

   <body>
        <div id="header">
        <h1>Animal Project</h1>
           <%= link_to 'Animals', animals_path %> 
            <%= link_to 'Diseases', diseases_path %> 
            <%= link_to 'Owners', owners_path %> 
            <%= link_to 'Date of Infections', date_infecteds_path %> 
        </div>
        <%= yield %>
    </body>

</html>

app/views/owners/_form.html.erb
<%= form_with(model: owner, local: true) do |form| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
        <% owner.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>